### PR TITLE
Fixed path variables from ZeroMQ_xxx to LIBZMQ_xxx in Findlibzmq.…

### PR DESCRIPTION
**Pull request by casabre**

### CODE REVIEW

**Comment by uilianries** [comment]
Hi @casabre are you using Conan cmake generator or cmake_find_package? I'm curious, because this is "old".

**Comment by casabre** [comment]
Hi @uilianries, I utilized the Conan cmake generator via the conanfile.py and it ended up always in the same error that the script is pretending to find the includes and libs but the variables were empty. Just figured out that the logged message came from that script. Thus it is was just plausible to me to change it.

I tried also to build the conan-czmq package but with the same result as with my conanfile.py. 
Just started with Conan packaging. It is more or less a clone of the conan-czmq repository &rarr; [conan-zyre](https://github.com/casabre/conan-zyre/tree/bincrafters-approach).  Was this approach wrong? Finally, my goal was also to transfer ownership maybe to bincrafters if it is packaging properly. Is this approach acceptable for you?

**Comment by uilianries** [comment]
@casabre thanks for your detailed description!

**Comment by uilianries** [comment]
@casabre about conan-zyre, you can try [Conan Center Index](https://github.com/conan-io/conan-center-index) instead. Please, read https://github.com/conan-io/conan-center-index/wiki#adding-packages-to-conancenter to get more information about.

**Pull request merged**
